#!/bin/bash
########################################################################################################################
# This script is able to install ROSE on a clean CentOS-7 machine, configuring ROSE for binary analysis
# (--enable-languages=binaries) along with a number of software packages that increase the feature set of the binary
# analysis.
#
# Prerequisite steps:
#
#  1. Create an AWS machine with a CentOS-7 AMI such as "CentOS 7 (x86_64) with Updates HVM". The machine should be
#     large enough, such as m5.4xlarge (16 CPUs, 64 GiB RAM). Enlarge the root file system to be at least 60 GiB.
#
#  2. Log in as a normal (non-root) user
#
#  3. Run "sudo yum -y install git"
#
#  4. Optionally copy Megachiropteran and/or ESTCP source code into the "megachiropteran" and "estcp-software"
#     directories. They will be built and installed if present.
#
#  5. Run "git clone https://github.com/matzke1/rose-installers"
#
#  6. Run "./rose-installers/install-binaryanalysis-centos7"
#
# If this script fails part way through, it's often possible to make adjustments to the system and then re-run this
# script after commenting out the steps at the end that have already been completed.
#
########################################################################################################################
set -e
arg0="${0##*/}"
dir0="${0%/*}"

. "${dir0}/impl/binaryanalysis-installation-support.sh"
export PATH="$HOME/.spock/bin:$PATH"

# These instructions come from https://rosecompiler.atlassian.net/wiki/x/vwBhF
install-system-dependencies() {
    ### WARNING: yum commands don't exit with non-zero status if they fail!!!!!!
    (
        set -x
        sudo yum -y update
 
        sudo yum -y install wget tar cmake java-1.8.0-openjdk-devel python-devel graphviz gcc-c++ flex bison \
             bzip2 zlib-devel libtool libtool-ltdl-devel byacc libgcrypt-devel xz \
             fuse fuse-devel passwd fontconfig mesa-libGLU git pcre-devel patch glibc-static libstdc++-static \
             libstdc++-devel.x86_64 ncurses-devel.i686 sudo postgresql-devel ghostscript time
    )

    while ! which scl; do
        # Often fails the first time it runs, so just try a few times
        sleep 5
        (set -x; sudo yum -y install centos-release-scl devtoolset-7)
    done

    (
        set -x

        # If you plan to build with Tup
        sudo chmod 4755 /bin/fusermount

        # SQLite's build system needs TCL
        sudo yum -y install tcl-devel
 
        # The following lines are needed for 7z if you're building binary releases of ROSE software. The version numbers change and the
	# old versions are removed from the download site. If you get errors here, use your web browser to list the directory mentioned
	# below and then fill in the correct P7_VERSION number.
	P7_VERSION=16.02-20
        wget https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/p7zip-${P7_VERSION}.el7.x86_64.rpm
        wget https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/p7zip-plugins-${P7_VERSION}.el7.x86_64.rpm
        sudo rpm -U --quiet p7zip-${P7_VERSION}.el7.x86_64.rpm
        sudo rpm -U --quiet p7zip-plugins-${P7_VERSION}.el7.x86_64.rpm
        rm p7zip-${P7_VERSION}.el7.x86_64.rpm p7zip-plugins-${P7_VERSION}.el7.x86_64.rpm

        # Additional utilities that are needed for building ROSE or dependencies. "file" is needed when moving artifacts to
        # the installation directories, and "rsync" is needed to copy extra files into artifact directories.
        sudo yum -y install file rsync
    )
}

# Some systems require extra commands to be run in each shell.
# These instructions come from https://rosecompiler.atlassian.net/wiki/x/vwBhF
run() {
    (
        set -x
        scl enable devtoolset-7 -- "$@"
    )
}

choose-rose-dependencies() {
    rm -rf rose/_build
    mkdir rose/_build
    # magic is not needed because it's not fully supported in Tup builds
    # libpqxx is disabled because the library doesn't get inserted into the binary release (ROSE-2592)
    # latest Tup versions require fuse3, not available on RHEL-7
    (cd rose/_build && BUILD=tup MAGIC=none PQXX=none TUP=0.7.9 run rmc init --project=binaries --batch ..)
    cat rose/_build/.rmc-main.cfg
}

########################################################################################################################

check-hardware-requirements 50000000
install-system-dependencies
install-rmc-spock
get-rose-source-code
choose-rose-dependencies
install-rose-dependencies
create-automake-files
configure-rose
build-test-install-rose
conditionally-install-megachiropteran
conditionally-install-estcp
conditionally-install-rose-garden
build-binary-release
compress-binary-release
