#!/bin/bash
########################################################################################################################
# This script is able to install ROSE on a clean CentOS-7 machine, configuring ROSE for Jovial, C, C++, and binary
# analysis (--enable-languages=binaries,c,c++ and additional switches for Jovial) along with a number of prerequisite
# software packages such as ATerm, Stratego, SDF2, and Java.
#
# Prerequisite steps:
#
#  1. Create a new CentOS-7 machine, such as an AWS machine with a CentOS-7 AMI such as "CentOS 7 (x86_64) with Updates
#     HVM". The machine should be large enough, such as m4.4xlarge (16 CPUs, 64 GiB RAM). Enlarge the root file system
#     to be at least 60 GiB.
#
#  2. Log in as a normal (non-root) user
#
#  3. Run "sudo yum -y install git"
#
#  4. Optionally copy Megachiropteran and/or ESTCP source code into the "megachiropteran" and "estcp-software"
#     directories. They will be built and installed if present.
#
#  5. Manually copy non-public prerequisite software packages into /software with the names listed below. You can find
#     these on the ROSE team's NFS server in the /usr/casc/overture/ROSE/opt/rhel7/x86_64/stratego directory (the OS and
#     ISA components of this path don't mean anything).
#
#       strategoxt-0.17.1.tar.gz
#       sdf2-bundle-2.4.1.tar.gz
#       aterm-3.0.tar.gz
#
#  6. Run "git clone https://github.com/matzke1/rose-installers"
#
#  7. Run "./rose-installers/install-release-centos7"
#
# If this script fails part way through, it's often possible to make adjustments to the system and then re-run this
# script after commenting out the steps at the end that have already been completed.
#
########################################################################################################################
set -e
arg0="${0##*/}"
dir0="${0%/*}"

. "${dir0}/impl/full-release.sh"
export PATH="$HOME/.spock/bin:$PATH"

# These instructions come from https://rosecompiler.atlassian.net/wiki/x/vwBhF
[[ override ]]
install-system-dependencies() {
    ### WARNING: yum commands don't exit with non-zero status if they fail!!!!!!
    (
        set -x
        sudo yum -y update
 
        sudo yum -y install wget tar cmake java-1.8.0-openjdk-devel python-devel graphviz gcc-c++ flex bison \
             bzip2 zlib-devel libtool libtool-ltdl-devel byacc libgcrypt-devel xz \
             fuse fuse-devel passwd fontconfig mesa-libGLU git pcre-devel patch glibc-static libstdc++-static \
             libstdc++-devel.i686 ncurses-devel.i686 sudo postgresql-devel ghostscript
    )

    while ! which scl; do
        # Often fails the first time it runs, so just try a few times
        sleep 5
        (set -x; sudo yum -y install centos-release-scl devtoolset-7)
    done

    (
        set -x

        # If you plan to build with Tup
        sudo chmod 4755 /bin/fusermount

        # SQLite's build system needs TCL
        sudo yum -y install tcl-devel
 
        # The following lines are needed for 7z if you're building binary releases of ROSE software
        wget https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/p7zip-16.02-10.el7.x86_64.rpm
        wget https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/p7zip-plugins-16.02-10.el7.x86_64.rpm
        sudo rpm -U --quiet p7zip-16.02-10.el7.x86_64.rpm
        sudo rpm -U --quiet p7zip-plugins-16.02-10.el7.x86_64.rpm
        rm p7zip-16.02-10.el7.x86_64.rpm p7zip-plugins-16.02-10.el7.x86_64.rpm

        # Additional utilities that are needed for building ROSE or dependencies. "file" is needed when moving artifacts to
        # the installation directories, and "rsync" is needed to copy extra files into artifact directories.
        sudo yum -y install file rsync
    )
}

# Some systems require extra commands to be run in each shell.
# These instructions come from https://rosecompiler.atlassian.net/wiki/x/vwBhF
[[ override ]]
run() {
    (
        set -x
        scl enable devtoolset-7 "$@"
    )
}

[[ override ]]
build-test-install-rose-garden() {
    # Extra level of escaping needed for quotes and dollar signs due to multiple nesting of "run", "rmc", and "bash -c".

    # Jovial
    run rmc -C rose/_build bash -c '
        export PATH=\"\$HOME/rose-installed/latest/bin:\$PATH\"
        cd ../../rose-garden/jovial-to-cpp/src
        make -j\$RMC_PARALLELISM
	make install
        '

    # attributeLib (which has no "make install" target)
    run rmc -C rose/_build bash -c '
        export PATH=\"\$HOME/rose-installed/latest/bin:\$PATH\"
        cd ../../rose-garden/attributeLib/src
        ROSE_HOME=\$HOME/rose-installed/latest BOOST_HOME=\$BOOST_ROOT make
        cp -p attributeLibIngest attributeLibMatch attributeLibWithSource \$HOME/rose-installed/latest/bin/.
        '
}

########################################################################################################################

check-hardware-requirements
install-system-dependencies
install-rmc-spock
get-rose-source-code
choose-rose-dependencies
install-rose-dependencies
create-automake-files
configure-rose
build-test-install-rose
conditionally-install-megachiropteran
conditionally-install-estcp
conditionally-install-rose-garden
build-binary-release
compress-binary-release
