#!/bin/bash
########################################################################################################################
# This script is able to install ROSE on a clean CentOS-8 machine, configuring ROSE for binary analysis
# (--enable-languages=binaries) along with a number of software packages that increase the feature set of the binary
# analysis.
#
# Prerequisite steps:
#
#  1. Create an AWS machine with a CentOS-8 AMI such as "CentOS 7 x86_64 HVM". The machine should be large enough, such
#     as m5.4xlarge (16 CPUs, 64 GiB RAM). Enlarge the root file system to be at least 60 GiB.
#
#  2. Log in as a normal (non-root) user
#
#  3. Run "sudo yum -y install git"
#
#  4. Optionally copy Megachiropteran and/or ESTCP source code into the "megachiropteran" and "estcp-software"
#     directories. They will be built and installed if present.
#
#  5. Run "git clone https://github.com/matzke1/rose-installers"
#
#  6. Run "./rose-installers/install-binaryanalysis-centos8"
#
# If this script fails part way through, it's often possible to make adjustments to the system and then re-run this
# script after commenting out the steps at the end that have already been completed.
#
########################################################################################################################
set -e
arg0="${0##*/}"
dir0="${0%/*}"

. "${dir0}/impl/binaryanalysis-installation-support.sh"
export PATH="$HOME/.spock/bin:$PATH"

# These instructions come from https://rosecompiler.atlassian.net/wiki/x/vwBhF
install-system-dependencies() {
    (
        set -x
        ### WARNING: yum commands don't exit with non-zero status if they fail!!!!!!
        sudo yum -y update
        sudo yum -y install wget tar cmake java-1.8.0-openjdk-devel graphviz gcc-c++ flex bison \
             bzip2 zlib-devel libtool libtool-ltdl-devel byacc libgcrypt-devel xz \
             fuse fuse-devel passwd fontconfig mesa-libGLU pcre-devel patch \
             postgresql-devel ghostscript make

        # Static libraries (needed by some ROSE dependencies)
        sudo dnf -y install langpacks-en glibc-all-langpacks
        sudo dnf -y install 'dnf-command(config-manager)'
        sudo dnf config-manager --enable PowerTools
        sudo yum -y install glibc-static libstdc++-static

        # The following lines are needed for 7z if you're building binary releases of ROSE software
        sudo dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        sudo rpm -ql epel-release
        sudo dnf repolist -v
        sudo dnf -y install p7zip p7zip-plugins

        # Additional utilities that are needed for building ROSE or dependencies. "texinfo" and "help2man" are needed to
        # install bison. "file" is needed when moving artifacts to the installation directories. "tcl-devel" is needed to
        # install SQLite.
        sudo dnf -y install diffutils file help2man rsync texinfo tcl-devel
    )
}

########################################################################################################################

check-hardware-requirements 50000000
install-system-dependencies
install-rmc-spock
get-rose-source-code
choose-rose-dependencies
install-rose-dependencies
create-automake-files
configure-rose
build-test-install-rose
conditionally-install-megachiropteran
conditionally-install-estcp
conditionally-install-rose-garden
build-binary-release
compress-binary-release
