#!/bin/bash
########################################################################################################################
# This script is able to install ROSE on a clean Mint-18 machine, configuring ROSE for binary analysis
# (--enable-languages=binaries) along with a number of software packages that increase the feature set of the binary
# analysis.
#
# Prerequisite steps:
#
#  1. Create a machine running Mint-18 (such as an AWS EC2 instance or a VirtualBox instance). The machine should be
#     large enough, such as 16 CPUs and 64 GiB RAM, and 60 GiB disk.
#
#  2. Log in as a normal (non-root) user.
#
#  3. Optionally copy Megachiropteran and/or ESTCP source code into the "megachiropteran" and "estcp-software"
#     directories. They will be built and installed if present.
#
#  4. Run "git clone https://github.com/matzke1/rose-installers"
#
#  5. Run "./rose-installers/install-binaryanalysis-mint18"
#
# If this script fails part way through, it's often possible to make adjustments to the system and then re-run this
# script after commenting out the steps at the end that have already been completed.
#
########################################################################################################################
set -e
arg0="${0##*/}"
dir0="${0%/*}"

. "${dir0}/impl/binaryanalysis-installation-support.sh"
export PATH="$HOME/.spock/bin:$PATH"

# These instructions come from https://rosecompiler.atlassian.net/wiki/x/vwBhF
install-system-dependencies() {
    sudo apt-get -y update
    sudo apt-get -y install git wget build-essential g++ gfortran libtool automake flex bison \
	graphviz-dev cmake libpqxx-dev ghostscript perl-doc groff libgcrypt20-dev \
	libfcgi-dev libfuse-dev patchelf gcc-multilib g++-multilib gfortran-multilib \
	fuse bsdmainutils libxapian-dev libltdl-dev

    # If building ROSE graphical user interfaces that use Qt
    sudo apt-get -y install qt5-default '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev \
	 libxrender-dev libxi-dev libfontconfig1-dev libatspi2.0-dev libdbus-1-dev
}

# Decide what software dependencies should be used when compiling ROSE.
choose-rose-dependencies() {
    rm -rf rose/_build
    mkdir rose/_build

    # Use a C++11 compiler instead of the default C++03. This allows us to use later versions of some dependencies.
    (cd rose/_build && BUILD=tup COMPILER=gnu-c++11 run rmc init --project=binaries --batch ..)
    cat rose/_build/.rmc-main.cfg
}

########################################################################################################################

check-hardware-requirements 25000000
install-system-dependencies
install-rmc-spock
get-rose-source-code
choose-rose-dependencies
install-rose-dependencies
create-automake-files
configure-rose
build-test-install-rose
conditionally-install-megachiropteran
conditionally-install-estcp
build-binary-release
compress-binary-release
